#!/bin/bash

tacoco_home=$(pwd)

cp -r ../projects4testing .

if [ $? -ne 0 ];
then
    echo "Failed to copy files from projects4testing..."
    exit 1
fi

cd $tacoco_home/projects4testing/spiderMath_Gradle && gradle build
cd $tacoco_home/projects4testing/spiderMath_JUnit && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
cd $tacoco_home/projects4testing/spiderMath_TestNG && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8

cd $tacoco_home
mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_Gradle -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_Gradle -Danalyzer.opts="configs/tacoco-analyzer.config"

if [ $? -ne 0 ];
then
    echo "Tacoco failed with spiderMath_Gradle..."
    exit 1
fi

mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_JUnit -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_JUnit -Danalyzer.opts="configs/tacoco-analyzer.config"

if [ $? -ne 0 ];
then
    echo "Tacoco failed with spiderMath_JUnit..."
    exit 1
fi

mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_TestNG -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_TestNG -Danalyzer.opts="configs/tacoco-analyzer.config" 

if [ $? -ne 0 ];
then
    echo "Tacoco failed with spiderMath_TestNG..."
    exit 1
fi

exit 0