#!/bin/bash

cd $1
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$1/target/test-classes:$1/target/classes:$CLASSPATH
echo $CLASSPATH

cd $2
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$2/target/test-classes:$2/target/classes:$CLASSPATH
echo $CLASSPATH
mvn dependency:copy-dependencies -DoutputDirectory=lib
java -javaagent:lib/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=jacoco.exec,dumponexit=false org.spideruci.tacoco.TacocoRunner $1/target/test-classes

