#!/bin/bash

project_name=$(echo $1 | rev | cut -d'/' -f 1 | rev)
echo $project_name

cd $2
echo "RUNNING TACOCO"
mvn exec:java -Plauncher -Dtacoco.sut=$1 -Dtacoco.home=$2 -Dtacoco.project=$project_name -Danalyzer.opts="configs/tacoco-analyzer.config"
echo "RUNNING TACOCO --- DONE"

echo "ANALYZING EXEC FILE"
mvn exec:java -Panalyzer -Dtacoco.sut=$1 -Dtacoco.exec=tacoco_output/$project_name.exec -Dtacoco.json=tacoco_output/$project_name.json -Dtacoco.pp
echo "ANALYZING EXEC FILE --- DONE"

echo "READING COVERAGE MATRIX"
mvn exec:java -Preader -Dtacoco.json=tacoco_output/$project_name.json -Dtacoco.pp
echo "READING COVERAGE MATRIX --- DONE"

# open "tacoco_output/$project_name-cov-matrix.json"
