#!/bin/bash

tacoco_home=./../

cd ../resources/
cd spiderMath_Gradle && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
cd ../spiderMath_JUnit && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
cd ../spiderMath_TestNG && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8

cd ../../scripts

cd $tacoco_home
mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/resources/spiderMath_Gradle -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_Gradle -Danalyzer.opts="configs/tacoco-analyzer.config"
RESULT_GRADLE=$?
mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/resources/spiderMath_JUnit -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_JUnit -Danalyzer.opts="configs/tacoco-analyzer.config"
RESULT_JUNIT=$?
mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/resources/spiderMath_TestNG -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_TestNG -Danalyzer.opts="configs/tacoco-analyzer.config" 
RESULT_TESTNG=$?

if [ RESULT_GRADLE -ne 0 ];
then
    echo "Tacoco failed with spiderMath_Gradle..."
    exit 1
if [ RESULT_JUNIT -ne 0 ];
then
    echo "Tacoco failed with spiderMath_JUnit..."
    exit 1
if [ RESULT_TESTNG -ne 0 ];
then
    echo "Tacoco failed with spiderMath_TestNG..."
    exit 1
fi

